# Generated by Django 5.1.3 on 2024-11-29 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricetarget',
            name='last_triggered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricetarget',
            name='direction',
            field=models.CharField(choices=[('above', 'Above'), ('below', 'Below'), ('exact', 'Exact')], max_length=5),
        ),
        migrations.AlterField(
            model_name='pricetarget',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stock'),
        ),
    ]
