# Generated by Django 5.1.3 on 2024-11-28 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100, null=True)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('previous_close', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('market_cap', models.BigIntegerField(null=True)),
                ('volume', models.BigIntegerField(null=True)),
                ('day_high', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('day_low', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PriceTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('direction', models.CharField(choices=[('above', 'Above'), ('below', 'Below')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_targets', to='core.stock')),
            ],
        ),
    ]
