# Generated by Django 5.1.3 on 2024-11-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pricetarget_last_triggered_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricetarget',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['symbol']},
        ),
        migrations.AlterField(
            model_name='pricetarget',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
